function goToGoal0()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=58, ["P1 Y Axis"]=-9})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=46, ["P1 Y Axis"]=-8})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=-66, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=35, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=36, ["P1 Y Axis"]=-7})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-67, ["P1 Y Axis"]=10})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=9, ["P1 Y Axis"]=58})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=-6, ["P1 Y Axis"]=-25})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=15, ["P1 Y Axis"]=121})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-15, ["P1 Y Axis"]=-120})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=15, ["P1 Y Axis"]=121})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-15, ["P1 Y Axis"]=-120})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=15, ["P1 Y Axis"]=121})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-15, ["P1 Y Axis"]=-120})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=15, ["P1 Y Axis"]=121})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-15, ["P1 Y Axis"]=-120})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	joypad.setanalog({["P1 X Axis"]=15, ["P1 Y Axis"]=121})
	emu.frameadvance()
	joypad.set({["P1 A"]="True"})
	emu.frameadvance()
	joypad.set({["P1 A"]="False"})
	joypad.setanalog({["P1 X Axis"]=-15, ["P1 Y Axis"]=-120})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=15, ["P1 Y Axis"]=121})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-6, ["P1 Y Axis"]=-25})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=-8, ["P1 Y Axis"]=-46})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=10, ["P1 Y Axis"]=67})
	emu.frameadvance()
	emu.frameadvance()
	joypad.setanalog({["P1 X Axis"]=0, ["P1 Y Axis"]=0})
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
	emu.frameadvance()
end
goToGoal0()

